name: Replacement
description: Recommend a replacement
title: '[Replacement]: '
labels: ['replacement', 'triage']
assignees:
  - 43081j
  - gameroman
  - joaopedrodcf
type: replacement
body:
  - type: textarea
    id: replacement
    attributes:
      label: Package to replace?
    validations:
      required: true
  - type: markdown
    id: description
    attributes:
      value: |
        Why do you want to replace X with Y
