name: Replacement
description: Recommend a replacement
title: '[Replacement]: '
labels: ['replacement', 'triage']
assignees:
  - octocat
  - octocat
type: replacement
body:
  - type: markdown
    id: description
    attributes:
      value: |
        Thanks for taking the time to fill out this replacement request!
  - type: textarea
    id: replacement
    attributes:
      label: Package to replace?
    validations:
      required: true
